Update ci_nextflow.yml

diff --git a/.github/workflows/ci_nextflow.yml b/.github/workflows/ci_nextflow.yml
--- a/.github/workflows/ci_nextflow.yml
+++ b/.github/workflows/ci_nextflow.yml
@@ -28,6 +28,13 @@ jobs:
           --velvetoptimiser false
           FILE=report/index.html 
           if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
+      - name: Basic workflow tests - long 
+        run: |
+          nextflow run ${GITHUB_WORKSPACE} -profile docker --fastq "test/data/tinyont.fastq.gz" \
+          --reference "test/data/tiny_reference.fasta" --max_cpus 2 --max_memory 4.GB \
+          --wf ont --flye false --metaflye false --ra false --wtdbg2 false --canu false
+          FILE=report/index.html 
+          if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
 
   singularity:
     runs-on: ubuntu-latest
@@ -53,5 +60,12 @@ jobs:
           --abyss false --gatb_minia false --idba false --metahipmer2 false \
           --minia false --megahit false --metaspades false --spades false --unicycler false \
           --velvetoptimiser false
+          FILE=report/index.html 
+          if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
+      - name: Basic workflow tests - long 
+        run: |
+          nextflow run ${GITHUB_WORKSPACE} -profile singularity --fastq "test/data/tinyont.fastq.gz" \
+          --reference "test/data/tiny_reference.fasta" --max_cpus 2 --max_memory 4.GB \
+          --wf ont --flye false --metaflye false --ra false --wtdbg2 false --canu false
           FILE=report/index.html 
           if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
