update ci with singularity test

diff --git a/.github/workflows/ci_nextflow.yml b/.github/workflows/ci_nextflow.yml
--- a/.github/workflows/ci_nextflow.yml
+++ b/.github/workflows/ci_nextflow.yml
@@ -7,7 +7,7 @@ on:
     branches: [ main ]
 
 jobs:
-  test:
+  docker:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -26,5 +26,32 @@ jobs:
           --abyss false --bcalm false --gatb_minia false --idba false --metahipmer2 false \
           --minia false --megahit false --metaspades false --spades false --unicycler false \
           --velvetoptimiser false
+          FILE=report/index.html 
+          if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
+
+  singularity:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        singularity_version: ['3.6.4']
+        nxf_ver: ['20.01.0', '']
+    steps:
+      - uses: actions/checkout@v1
+      - uses: eWaterCycle/setup-singularity@v6
+        with:
+          singularity-version: ${{ matrix.singularity_version }}
+      - name: Install Nextflow
+        run: |
+          export NXF_VER=${{ matrix.nxf_ver }}
+          wget -qO- get.nextflow.io | bash
+          sudo mv nextflow /usr/local/bin/
+      - name: Basic workflow tests
+        run: |
+          nextflow run ${GITHUB_WORKSPACE} -profile docker --fastq "test/data/tiny_{1,2}.*" \
+          --reference "test/data/tiny_reference.fasta" --max_cpus 2 --max_memory 4.GB \
+          --abyss false --bcalm false --gatb_minia false --idba false --metahipmer2 false \
+          --minia false --megahit false --metaspades false --spades false --unicycler false \
+          --velvetoptimiser false -with-singularity
           FILE=report/index.html 
           if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
