start longlmas dev

diff --git a/.github/workflows/ci_nextflow.yml b/.github/workflows/ci_nextflow.yml
--- a/.github/workflows/ci_nextflow.yml
+++ b/.github/workflows/ci_nextflow.yml
@@ -19,12 +19,19 @@ jobs:
           export NXF_VER=${{ matrix.nxf_ver }}
           wget -qO- get.nextflow.io | bash
           sudo mv nextflow /usr/local/bin/
-      - name: Basic workflow tests
+      - name: Basic workflow tests - default 
         run: |
           nextflow run ${GITHUB_WORKSPACE} -profile docker --fastq "test/data/tiny_{1,2}.*" \
           --reference "test/data/tiny_reference.fasta" --max_cpus 2 --max_memory 4.GB \
           --abyss false --bcalm false --gatb_minia false --idba false --metahipmer2 false \
           --minia false --megahit false --metaspades false --spades false --unicycler false \
           --velvetoptimiser false
+          FILE=report/index.html 
+          if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
+      - name: Basic workflow tests - long 
+        run: |
+          nextflow run ${GITHUB_WORKSPACE} -profile docker --fastq "test/data/tiny_longreads.fastq.gz" \
+          --reference "test/data/tiny_reference.fasta" --max_cpus 2 --max_memory 4.GB \
+          --wf long --flye false --metaflye false --ra false --wtdbg2 false
           FILE=report/index.html 
           if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
