add feedback for successful run

diff --git a/.github/workflows/ci_nextflow.yml b/.github/workflows/ci_nextflow.yml
--- a/.github/workflows/ci_nextflow.yml
+++ b/.github/workflows/ci_nextflow.yml
@@ -27,4 +27,4 @@ jobs:
           --minia false --megahit false --metaspades false --spades false --unicycler false \
           --velvetoptimiser false
           FILE=report/index.html 
-          if [ ! -f "$FILE" ]; then echo "Run failed"; exit 1; fi
+          if [ ! -f "$FILE" ]; then echo "Run failed!"; exit 1; else echo "Run successful!"; fi
