fix process name in conf/containers.config; add check that workflow completed successfully by checking that report file exists

diff --git a/.github/workflows/ci_nextflow.yml b/.github/workflows/ci_nextflow.yml
--- a/.github/workflows/ci_nextflow.yml
+++ b/.github/workflows/ci_nextflow.yml
@@ -21,8 +21,10 @@ jobs:
           sudo mv nextflow /usr/local/bin/
       - name: Basic workflow tests
         run: |
-          eval nextflow run ${GITHUB_WORKSPACE} -profile docker --fastq "test/data/tiny_{1,2}.*" \
+          nextflow run ${GITHUB_WORKSPACE} -profile docker --fastq "test/data/tiny_{1,2}.*" \
           --reference "test/data/tiny_reference.fasta" --max_cpus 2 --max_memory 4.GB \
           --abyss false --bcalm false --gatb_minia false --idba false --metahipmer2 false \
           --minia false --megahit false --metaspades false --spades false --unicycler false \
           --velvetoptimiser false
+          FILE=report/index.html 
+          if [ ! -f "$FILE" ]; then echo "Run failed"; exit 1; fi
